### ISSUE TITLE
Solver changes

### ISSUE THREAD

**Issue by ducha-aiki** [forestagostinelli/Learned-Activation-Functions-Source#3]
Hi,

I am doing activation benchmark https://github.com/ducha-aiki/caffenet-benchmark/blob/master/Activations.md and I`d like to test APL as well. My question is - how much necessary are the changes to solver? Is it possible to use APL without them? 
I am asking because would like to test everything with in same conditions.

**Comment by forestagostinelli** [comment]
You should be able to use the APL units without changing your solver file.
Please let me know if you run into any problems.

**Comment by ducha-aiki** [comment]
Thank you!

**Comment by ducha-aiki** [comment]
Here are bechmarking results.
https://github.com/ducha-aiki/caffenet-benchmark/blob/master/Activations.md
If you update implementation to the parameter sharing setup, I will be happy to test it one more time :)

**Comment by forestagostinelli** [comment]
Thanks a lot! This is very helpful!
